version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependency...
      - yarn install
  build:
    commands:
      - yarn test:ci
      - yarn build
      - aws s3 rm -recursive "s3://${ARTIFACTS_BUCKET}/"
artifacts:
  files:
    - "**/*"
  base-directory: build
